### ISSUE TITLE
Proposal: dict config

### ISSUE THREAD

**Issue by svartalf** [martinrusev/django-redis-sessions#18]
Since dictionary configs become very popular (like `django.conf.settings.DATABASES`) or `logging` [configuration style](http://www.python.org/dev/peps/pep-0391/), shouldn't it be better to make one setting like a `SESSION_REDIS` which will looks like this?

```
SESSION_REDIS = {
    'HOST': 'localhost',
    'PORT': 6379,
    'DB': 0,
    'PREFIX': 'session',
}
```

Also, like in a Django, if `HOST` starts with a '/', it would assumes, that it is an Unix socket, and empty string should assumes an `localhost` address.

**Comment by thiagoghisi** [comment]
That would be great! :+1:

**Comment by merwok** [comment]
As long as one can create a dict from an environment variable!

**Comment by martinrusev** [comment]
Supported in the latest release 0.6.
Configuration through env variables will be considered for a next release

**Comment by caseydm** [comment]
Hi all. Just to clarify, does this update break the ability to use URL style config from environment variables? Just want to make sure I understand correctly, and vote to include this feature in the next release since I cannot upgrade past 0.5.0 until it is available.
