### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by arthurk** [martinrusev/django-redis-sessions#38]
Hi Martin,

would it be possible to make a new release? The sentinel features are very interesting

Thanks!

**Comment by martinrusev** [comment]
@arthurk Will get to that this weekend and will close the ticket when it is done

**Comment by martinrusev** [comment]
@arthurk Done

**Comment by arthurk** [comment]
@martinrusev thanks!

**Comment by arthurk** [comment]
@martinrusev there seems to be an issue, please see https://github.com/martinrusev/django-redis-sessions/issues/39 for more information
