### ISSUE TITLE
build failing with IOError (cannot find README)

### ISSUE THREAD

**Issue by arthurk** [martinrusev/django-redis-sessions#39]
When trying to install the current build for version 0.5.5 with `pip install django-redis-sessions` it fails with:

```
IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Y06Tjv/django-redis-sessions/README.md'
```

It also shows up in Travis: https://travis-ci.org/martinrusev/django-redis-sessions/jobs/136061874

**Comment by ahopkins** [comment]
Yup, I'm getting the same as well.

    Collecting django-redis-sessions
    Using cached django-redis-sessions-0.5.5.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-ty0UR4/django-redis-sessions/setup.py", line 15, in <module>
          long_description=read("README.md"),
        File "/tmp/pip-build-ty0UR4/django-redis-sessions/setup.py", line 6, in read
          return open(os.path.join(os.path.dirname(__file__), filename)).read()
      IOError: [Errno 2] No such file or directory: '/tmp/pip-build-ty0UR4/django-redis-sessions/README.md'
      
      ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ty0UR4/django-redis-sessions/

**Comment by martinrusev** [comment]
@ahopkins, @arthurk Fixed and pushed a working release to pypi
