### ISSUE TITLE
Update sessionid expires value

### ISSUE THREAD

**Issue by sodrian** [martinrusev/django-redis-sessions#40]
Hey!

I use django-redis-sessions for session backend, here is my configuration:

```
SESSION_CACHE_ALIAS = 'redis'
SESSION_COOKIE_AGE = 3600 * 24 * 7
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

CACHES = {
    'redis': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': '{0}:{1}'.format(REDIS_HOST, REDIS_PORT),
    }
}
```

The problem here is that sessionid key in cookies does not update and lives precisely for 1 week and users have to relogin every week.

Is there a way for sessionid to autoupdate on every request from user?

**Comment by nuarhu** [comment]
Why did you close this? Is this solved for you?
We do have the same problem. Could you share your solution?

**Comment by martinrusev** [comment]
@nuarhu How about this one: https://stackoverflow.com/questions/3044799/in-django-how-to-renew-expiry-date-for-current-session

**Comment by nuarhu** [comment]
I've added this setting: `SESSION_SAVE_EVERY_REQUEST = True` and that did the trick. Thanks for the quick answer and the link, it had the solution!
