### ISSUE TITLE
Release tags in github?

### ISSUE THREAD

**Issue by miketheman** [martinrusev/django-redis-sessions#44]
Hi there!

We use the library and since the changelog only contains the most recent release 0.5.6, I was wondering if you'd possibly add tags to when each release was cut so as to allow for better inspection of a given version.

I recognize this might be harder to go back, but starting with the current release would be enough to get started.

Thanks!

**Comment by martinrusev** [comment]
@miketheman Whenever there is a new release, I will tag it - no problem at all, I tag all my other open source projects anyway.

**Comment by miketheman** [comment]
Thanks!
