### ISSUE TITLE
Settings file broken

### ISSUE THREAD

**Issue by dbreen** [martinrusev/django-redis-sessions#48]
The settings.py file is trying to pull each setting from a dict, but it's calling `getattr` which will not work, so it always uses the defaults.

E.g.,

`SESSION_REDIS_HOST = getattr(SESSION_REDIS, 'host', 'localhost')`

Should be:

`SESSION_REDIS_HOST = SESSION_REDIS.get('host', 'localhost')`

**Comment by martinrusev** [comment]
@dbreen Should be fixed now

**Comment by dbreen** [comment]
Thanks! That fixed it.
